# Define accompanying passwords/secrets in group_vars/development/vault.yml
cake_apps:
  j24-games.test:
    site_hosts:
      - canonical: j24-games.test
        redirects:
          - www.j24-games.test
    local_path: ../cake # path targeting app directory (relative to Ansible root)
    ssl:
      enabled: true
      provider: self-signed
    env:
      app_debug: true