---
- name: disable temporary challenge sites
  file:
    path: "{{ nginx_path }}/sites-enabled/letsencrypt-{{ item }}.conf"
    state: absent
  with_items: "{{ cake_apps.keys() }}"
  notify: reload nginx
